config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ########
  # TOYS #
  ########

  # GET all toys
  get "/toys", to: "toys#index", as: "toys"

  # POST new toy
  post "/toys", to: "toys#create"

  # GET new toy form page
  get "/toys/new", to: "toys#new", as: "new_toy"

  # GET toy by id
  get "/toys/:id", to: "toys#show", as: "toy"

  # GET edit toy form page
  get "/toys/:id/edit", to: "toys#edit", as: "edit_toy"

  # PUT toy by id
  put "/toys/:id", to: "toys#update"
  patch "/toys/:id", to: "toys#update"

  # DELETE toy by id
  delete "/toys/:id", to: "toys#destroy"

  #########
  # USERS #
  #########

  # POST new users
  post "/users", to: "users#create", as: "users"

  # GET new user form page
  get "/users/new", to: "users#new", as: "new_user"

  # GET user by id
  get "/users/:id", to: "users#show", as: "user"

  # GET edit user page
  get "/users/:id/edit", to: "users#edit", as: "edit_user"

  # PUT user by id
  put "/users/:id", to: "users#update"
  patch "/users/:id", to: "users#update"

  # DELETE user by id
  delete "/users/:id", to: "users#destroy"

  #################
  # MANUFACTURERS #
  #################

  # GET all manufacturers
  get "/manufacturers", to: "manufacturers#index", as: "manufacturers"

  # POST new manufacturer
  post "/manufacturers", to: "manufacturers#create"

  # GET new manufacturer form page
  get "/manufacturers/new", to: "manufacturers#new", as: "new_manufacturer"

  # GET manufacturer by id
  get "/manufacturers/:id", to: "manufacturers#show", as: "manufacturer"

  # GET edit manufacturer form page
  get "/manufacturers/:id/edit", to: "manufacturers#edit", as: "edit_manufacturer"

  # PUT manufacturer by id
  put "/manufacturers/:id", to: "manufacturers#update"
  patch "/manufacturers/:id", to: "manufacturers#update"

  # DELETE manufacturer by id
  delete "/manufacturers/:id", to: "manufacturers#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_toy.rb
class CategoriesToy < ApplicationRecord
  belongs_to :category
  belongs_to :toy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_toys
  has_many :toys, through: :categories_toys
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :toys, dependent: :destroy
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :user
  belongs_to :manufacturer
  has_many :categories_toys
  has_many :categories, through: :categories_toys
end

app/models/user.rb
class User < ApplicationRecord
  has_many :toys, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    
  end

  def create
    @manufacturer = Manufacturer.create(manufacturer_params)
    redirect_to :action => "index"
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.update(manufacturer_params)
    redirect_to @manufacturer
  end

  def destroy
    Manufacturer.find(params[:id]).destroy

    redirect_to :action => "index"
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :location)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end

  def show
    @toy = Toy.find(params[:id])
  end
  
  def new
    
  end

  def create
    Toy.create(
      name: params[:toy][:name],
      description: params[:toy][:description],
      post_date: Date.today
    )

    redirect_to :action => "index"
  end

  def edit
    @toy = Toy.find(params[:id])
  end

  def update
    @toy = Toy.find(params[:id])
    @toy.update(params.require(:toy).permit(:name, :description))
    p params[:toy]

    redirect_to toy_url(@toy)
  end

  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy
    redirect_to :action => "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    @user = User.create(user_params)
    redirect_to @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to :controller => "toys", :action => "index"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Toy Store</h1>
    <ul>
      <li>
        <%= link_to 'Home', toys_path %>
      </li>
      <li>
        <%= link_to 'Manufacturers', manufacturers_path %>
      </li>
      <li>
        <%= link_to 'New User', new_user_path %>
      </li>
      <li>
        <%= link_to 'New Toy Listing', new_toy_path %>
      </li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/edit.html.erb
<form action="<%= manufacturer_path(params[:id]) %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">
  <input type="hidden" name="_method" value="put">

  <label for="name">Name</label>
  <input id="name" type="name" name="manufacturer[name]" value="<%= @manufacturer.name %>">

  <label for="location">Location</label>
  <input id="location" type="location" name="manufacturer[location]" value="<%= @manufacturer.location %>">

  <button>Submit</button>
</form>

app/views/manufacturers/index.html.erb
<%= link_to 'Create new manufacturer', new_manufacturer_path %>

<ul>
  <% @manufacturers.each do |manufacturer| %>
    <li>
      <h2><%= manufacturer.name %></h2>
      <h3><%= manufacturer.location %></h3>
      <%= link_to 'See manufacturer', manufacturer_path(manufacturer) %>
    </li>
  <% end %>
</ul>

app/views/manufacturers/new.html.erb
<form action="<%= manufacturers_path %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">

  <label for="name">Name</label>
  <input id="name" type="text" name="manufacturer[name]">

  <label for="location">Location</label>
  <input id="location" type="text" name="manufacturer[location]">

  <button>Submit</button>
</form>

app/views/manufacturers/show.html.erb
<h1><%= @manufacturer["name"] %></h1>
<h2><%= @manufacturer["location"] %></h2>

<ul>
  <% @manufacturer.toys.each do |toy| %>
    <li>
      <h3><%= toy.name %></h3>
      <h4>User: <%= toy.user.email %></h4>
      <p><%= toy.description %></p>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_manufacturer_path %>
<%= link_to 'Delete', manufacturer_path(@manufacturer),
    method: :delete,
    data: { confirm: "Are you sure?" }%>
<%= link_to 'Back', manufacturers_path %>

app/views/toys/edit.html.erb
<form action="<%= toy_path(params[:id]) %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">
  <input type="hidden" name="_method" value="put">

  <label for="name">Name</label>
  <input id="name" type="text" name="toy[name]" value="<%= @toy.name %>">

  <label for="description">Description</label>
  <textarea name="toy[description]" id="description" cols="30" rows="10"><%= @toy.description %></textarea>

  <button>Submit</button>
</form>

app/views/toys/index.html.erb
<h1>Toys Listings</h1>

<% @toys.each do |toy| %>
  <div>
    <h2><%= toy["name"] %></h2>
    <p><%= toy["post_date"] %></p>
    <p><%= toy["description"] %></p>
    <%= link_to 'View Toy', toy_path(toy) %>
  </div>
<% end %>

app/views/toys/new.html.erb
<form action="<%= toys_path %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">

  <label for="name">Name</label>
  <input id="name" type="text" name="toy[name]">

  <label for="description">Description</label>
  <textarea name="toy[description]" id="description" cols="30" rows="10"></textarea>

  <button>Submit</button>
</form>

app/views/toys/show.html.erb
<h1><%= @toy["name"] %></h1>
<p><%= @toy["post_date"] %></p>
<p><%= @toy["description"] %></p>

<%= link_to 'Edit', edit_toy_path %>
<%= link_to 'Delete', toy_path(@toy),
    method: :delete,
    data: { confirm: "Are you sure?" }%>
<%= link_to 'Back', toys_path %>

app/views/users/edit.html.erb
<form action="<%= user_path(params[:id]) %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">
  <input type="hidden" name="_method" value="put">

  <label for="email">Email</label>
  <input id="email" type="email" name="user[email]" value="<%= @user.email %>">

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]" value="<%= @user.password %>">

  <button>Submit</button>
</form>

app/views/users/new.html.erb
<form action="<%= users_path %>" method="POST">
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token">

  <label for="email">Email</label>
  <input id="email" type="email" name="user[email]">

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]">

  <button>Submit</button>
</form>

app/views/users/show.html.erb
<h1>Welcome, <%= @user["email"] %></h1>

<%= link_to 'Edit', edit_user_path %>
<%= link_to 'Delete', user_path(@user),
    method: :delete,
    data: { confirm: "Are you sure?" }%>
<%= link_to 'Home', toys_path %>